email: huangyk@aisi.ac.cn
description: >- 
  For higher efficiency and precision of ABACUS calculation!
baseurl: "/ABACUS-Pseudopot-Nao-Square"
url: "https://kirk0830.github.io"
github_username: kirk0830
#theme: minima
plugins:
  - jekyll-feed
email: huangyk@aisi.ac.cn